// The bundled sample questionnaires in /samples (generated by `npm run samples`).
import { promises as fs } from "fs";
import path from "path";

const SAMPLES_DIR = path.join(process.cwd(), "samples");

export async function listSamples(): Promise<string[]> {
  try {
    return (await fs.readdir(SAMPLES_DIR)).filter((f) => f.toLowerCase().endsWith(".pdf")).sort();
  } catch {
    return [];
  }
}

/** Only names from listSamples() are read, so a request can't escape the folder. */
export async function readSample(name: string): Promise<Buffer | null> {
  if (!(await listSamples()).includes(name)) return null;
  return fs.readFile(path.join(SAMPLES_DIR, name));
}
